### ISSUE TITLE
Test Notification doesn't seem to work

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyEventBroker#11]
I set up a listener + subscription to a target that sends Firebase Notifications. It works and I get the notifications.
When trying to invoke said target with the `https://sky.coflnet.com/api/notifications/targets/test` endpoint, I don't get a notification.

**Comment by Ekwav** [comment]
Do you have any way for me to get a Firebase token to reproduce that issue?

**Comment by matthias-luger** [comment]
Check out the "new-subscription-system" branch and create a firebase target.
Then it is stored in the localstorage -> `localStorage.getItem('fcmToken')`
