### ISSUE TITLE
When doesn't seem to be set correctly

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyEventBroker#12]
The field "when" of notification targets doesn't seem to be set correctly.

"ALWAYS" and "NEVER" seem to work as expected. I can set it as a string and the corresponding Enum-Numbers get returned afterwards ("ALWAYS" -> 2 and "NEVER" -> 0).

But "AFTER_FAIL" also returns 0, even though I would it expect to return 1.

**Comment by Ekwav** [comment]
Should be fixed, please verify yourself

**Comment by matthias-luger** [comment]
`Error converting value "AFTER_FAIL" to type 'Coflnet.Sky.Api.Models.Notifications.NotificationTarget+NotifyWhen'. Path 'when', line 1, position 228.`

Trace: 00-0ca6dbb525a99a4e59fff7aa994a2b87-586751cbd385c8d2-00

**Comment by Ekwav** [comment]
AFTER_ALL is not valid, maybe you meant AfterAll

**Comment by matthias-luger** [comment]
I assume you mean AfterFail. If so, yes it works now
