### ISSUE TITLE
Listener don't include the id

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyEventBroker#13]
The listener endpoints don't return the ids of the listeners. I need them to create subscriptions

**Comment by matthias-luger** [comment]
@Ekwav  
While this issue is fixed, now listeners don't seem to be created at all.
The POST request is successfull, but afterwards I receive no listeners.

![grafik](https://github.com/Coflnet/SkyEventBroker/assets/58751503/aefc00d6-f981-4a17-9004-91c894448832)
![grafik](https://github.com/Coflnet/SkyEventBroker/assets/58751503/3baa15fb-c37c-49ac-ace0-5ccb1e93e082)

Just to show that it was sent correctly, the subscription did work:
![grafik](https://github.com/Coflnet/SkyEventBroker/assets/58751503/3e92ecfe-f8f4-4e02-8167-eabab38c1898)
![grafik](https://github.com/Coflnet/SkyEventBroker/assets/58751503/39aa0f56-45fc-4609-90c7-e580cf2ee601)

**Comment by Ekwav** [comment]
Thanks for noting fixed with https://github.com/Coflnet/SkyApi/commit/e8022245c6e77c65c8da44878eee1d7a238c0c1b

**Comment by matthias-luger** [comment]
this seems to be fixed, thanks :)
